version: '3'
networks:
  development:
volumes:
  db_data:
  gem_cache:
  shared_data:
services:
  db:
    image: postgres:12.5-alpine
    container_name: app_db
    volumes:
      - db_data:/var/lib/postgresql/data
      - shared_data:/var/shared
    networks:
      - development
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - 5432:5432
  web:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: app_web
    volumes:
      - .:/var/app
      - shared_data:/var/shared
      - gem_cache:/user/local/bundle/gems
    networks:
      - development
    ports:
      - 3000:3000
    stdin_open: true
    tty: true
    env_file: .env.development
    entrypoint: dev-entrypoint.sh
    command: ['rails','s','-p','3000','-b','0.0.0.0']
    environment:
      RAILS_ENV: development
    depends_on:
      - db
    